# Generated by Django 5.1.7 on 2025-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_numbers', models.IntegerField()),
                ('items', models.TextField()),
                ('total_price', models.FloatField()),
                ('status', models.TextField()),
            ],
        ),
    ]
